#!/usr/bin/env python3
"""
MDOC file reader for SerialEM metadata files.

This module provides functions to read and parse .mdoc files generated by SerialEM,
organizing the data by ZValue sections for easy access.
"""

import re
from pathlib import Path
from typing import Dict, Any, Union, Optional


def parse_mdoc_file(mdoc_path: Union[str, Path]) -> Dict[str, Any]:
    """
    Parse an mdoc file and return structured data organized by ZValue.

    Args:
        mdoc_path: Path to the .mdoc file

    Returns:
        Dictionary with structure:
        {
            'header': {key: value, ...},
            'z_sections': {
                0: {key: value, ...},
                1: {key: value, ...},
                ...
            }
        }

    Raises:
        FileNotFoundError: If the mdoc file doesn't exist
        ValueError: If the file format is invalid
    """
    mdoc_path = Path(mdoc_path)

    if not mdoc_path.exists():
        raise FileNotFoundError(f"MDOC file not found: {mdoc_path}")

    if not mdoc_path.suffix.lower() == '.mdoc':
        raise ValueError(f"Expected .mdoc file, got: {mdoc_path.suffix}")

    result = {'header': {}, 'z_sections': {}}

    current_section = 'header'
    current_z_value = None

    with open(mdoc_path, 'r', encoding='utf-8') as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()

            if not line or line.startswith('[T = '):
                continue

            z_match = re.match(r'\[ZValue = (\d+)\]', line)
            if z_match:
                current_z_value = int(z_match.group(1))
                current_section = 'z_section'
                result['z_sections'][current_z_value] = {}
                continue

            if '=' in line:
                try:
                    key, value = line.split('=', 1)
                    key = key.strip()
                    value = value.strip()
                    parsed_value = _parse_value(value)

                    if current_section == 'header':
                        result['header'][key] = parsed_value
                    elif current_section == 'z_section' and current_z_value is not None:
                        result['z_sections'][current_z_value][key] = parsed_value

                except Exception as e:
                    print(f"Warning: Failed to parse line {line_num}: {line} - {e}")
                    continue

    return result


def _parse_value(value_str: str) -> Any:
    """Parse a string value and convert to appropriate Python type."""
    value_str = value_str.strip()

    if not value_str:
        return ""

    if ' ' in value_str:
        parts = value_str.split()
        try:
            numeric_parts = []
            for part in parts:
                if '.' in part:
                    numeric_parts.append(float(part))
                else:
                    numeric_parts.append(int(part))
            return numeric_parts
        except ValueError:
            return value_str

    try:
        if '.' not in value_str and value_str.lstrip('-').isdigit():
            return int(value_str)
        try:
            return float(value_str)
        except ValueError:
            pass
    except ValueError:
        pass

    return value_str


def get_z_section(mdoc_data: Dict[str, Any], z_value: int) -> Optional[Dict[str, Any]]:
    """Get data for a specific ZValue from parsed mdoc data."""
    return mdoc_data['z_sections'].get(z_value)


def get_all_z_values(mdoc_data: Dict[str, Any]) -> list:
    """Get all available ZValue indices from parsed mdoc data."""
    return sorted(mdoc_data['z_sections'].keys())


def get_tilt_angles(mdoc_data: Dict[str, Any]) -> Dict[int, float]:
    """Extract tilt angles for all Z sections."""
    tilt_angles = {}
    for z_value, data in mdoc_data['z_sections'].items():
        if 'TiltAngle' in data:
            tilt_angles[z_value] = data['TiltAngle']
    return tilt_angles


def get_subframe_paths(mdoc_data: Dict[str, Any]) -> Dict[int, str]:
    """Extract SubFramePath for all Z sections."""
    subframe_paths = {}
    for z_value, data in mdoc_data['z_sections'].items():
        if 'SubFramePath' in data:
            subframe_paths[z_value] = data['SubFramePath']
    return subframe_paths


def find_z_by_tilt_angle(mdoc_data: Dict[str, Any], target_angle: float, tolerance: float = 0.1) -> Optional[int]:
    """Find the ZValue that corresponds to a specific tilt angle."""
    best_match = None
    best_diff = float('inf')

    for z_value, data in mdoc_data['z_sections'].items():
        if 'TiltAngle' in data:
            angle_diff = abs(data['TiltAngle'] - target_angle)
            if angle_diff <= tolerance and angle_diff < best_diff:
                best_match = z_value
                best_diff = angle_diff

    return best_match


def get_z_section_by_tilt(mdoc_data: Dict[str, Any], target_angle: float, tolerance: float = 0.1) -> Optional[Dict[str, Any]]:
    """Get mdoc section data for a specific tilt angle."""
    z_value = find_z_by_tilt_angle(mdoc_data, target_angle, tolerance)
    if z_value is not None:
        return mdoc_data['z_sections'][z_value]
    return None


def find_closest_tilt_angles(mdoc_data: Dict[str, Any], target_angle: float, num_closest: int = 1) -> list:
    """Find the N closest tilt angles to a target angle."""
    matches = []
    for z_value, data in mdoc_data['z_sections'].items():
        if 'TiltAngle' in data:
            angle_diff = abs(data['TiltAngle'] - target_angle)
            matches.append((z_value, data['TiltAngle'], angle_diff))
    matches.sort(key=lambda x: x[2])
    return matches[:num_closest]


def get_tilt_angle_range(mdoc_data: Dict[str, Any], min_angle: float, max_angle: float) -> Dict[int, float]:
    """Get all ZValues and tilt angles within a specified range."""
    tilt_range = {}
    for z_value, data in mdoc_data['z_sections'].items():
        if 'TiltAngle' in data:
            angle = data['TiltAngle']
            if min_angle <= angle <= max_angle:
                tilt_range[z_value] = angle
    return tilt_range


def _format_value_for_mdoc(value: Any) -> str:
    """Format a Python value for writing to mdoc file."""
    if isinstance(value, list):
        formatted_parts = []
        for part in value:
            if isinstance(part, float):
                formatted_parts.append(f"{part}")
            else:
                formatted_parts.append(str(part))
        return " ".join(formatted_parts)
    elif isinstance(value, float):
        return f"{value}"
    elif isinstance(value, int):
        return str(value)
    else:
        return str(value)


def set_header_value(mdoc_data: Dict[str, Any], key: str, value: Any) -> None:
    """Set a value in the header section of mdoc data."""
    mdoc_data['header'][key] = value


def set_z_section_value(mdoc_data: Dict[str, Any], z_value: int, key: str, value: Any) -> bool:
    """Set a value in a specific Z section of mdoc data."""
    if z_value not in mdoc_data['z_sections']:
        return False
    mdoc_data['z_sections'][z_value][key] = value
    return True


def set_value_by_tilt_angle(mdoc_data: Dict[str, Any], target_angle: float, key: str, value: Any, tolerance: float = 0.1) -> bool:
    """Set a value in the Z section that matches a specific tilt angle."""
    z_value = find_z_by_tilt_angle(mdoc_data, target_angle, tolerance)
    if z_value is not None:
        mdoc_data['z_sections'][z_value][key] = value
        return True
    return False


def update_multiple_z_sections(mdoc_data: Dict[str, Any], updates: Dict[int, Dict[str, Any]]) -> Dict[int, bool]:
    """Update multiple Z sections with different values."""
    results = {}
    for z_value, section_updates in updates.items():
        if z_value in mdoc_data['z_sections']:
            for key, value in section_updates.items():
                mdoc_data['z_sections'][z_value][key] = value
            results[z_value] = True
        else:
            results[z_value] = False
    return results


def update_all_z_sections(mdoc_data: Dict[str, Any], key: str, value: Any) -> int:
    """Update a specific key in ALL Z sections."""
    count = 0
    for z_value in mdoc_data['z_sections']:
        mdoc_data['z_sections'][z_value][key] = value
        count += 1
    return count


def update_tilt_range(mdoc_data: Dict[str, Any], min_angle: float, max_angle: float, key: str, value: Any) -> int:
    """Update a specific key for all Z sections within a tilt angle range."""
    tilt_range = get_tilt_angle_range(mdoc_data, min_angle, max_angle)
    count = 0
    for z_value in tilt_range.keys():
        mdoc_data['z_sections'][z_value][key] = value
        count += 1
    return count


def add_z_section(mdoc_data: Dict[str, Any], z_value: int, section_data: Dict[str, Any], overwrite: bool = False) -> bool:
    """Add a new Z section to the mdoc data."""
    if z_value in mdoc_data['z_sections'] and not overwrite:
        return False
    mdoc_data['z_sections'][z_value] = section_data.copy()
    return True


def create_z_section_from_template(mdoc_data: Dict[str, Any], template_z_value: int,
                                   new_z_value: int, modifications: Optional[Dict[str, Any]] = None,
                                   overwrite: bool = False) -> bool:
    """Create a new Z section based on an existing section as a template."""
    if template_z_value not in mdoc_data['z_sections']:
        return False
    if new_z_value in mdoc_data['z_sections'] and not overwrite:
        return False

    new_section = mdoc_data['z_sections'][template_z_value].copy()
    if modifications:
        for key, value in modifications.items():
            new_section[key] = value

    mdoc_data['z_sections'][new_z_value] = new_section
    return True


def delete_z_section(mdoc_data: Dict[str, Any], z_value: int) -> bool:
    """Delete a Z section from the mdoc data."""
    if z_value not in mdoc_data['z_sections']:
        return False
    del mdoc_data['z_sections'][z_value]
    return True


def delete_multiple_z_sections(mdoc_data: Dict[str, Any], z_values: list) -> Dict[int, bool]:
    """Delete multiple Z sections from the mdoc data."""
    results = {}
    for z_value in z_values:
        results[z_value] = delete_z_section(mdoc_data, z_value)
    return results


def delete_z_sections_by_tilt_range(mdoc_data: Dict[str, Any], min_angle: float, max_angle: float) -> int:
    """Delete all Z sections within a tilt angle range."""
    tilt_range = get_tilt_angle_range(mdoc_data, min_angle, max_angle)
    z_values_to_delete = list(tilt_range.keys())
    count = 0
    for z_value in z_values_to_delete:
        if delete_z_section(mdoc_data, z_value):
            count += 1
    return count


def renumber_z_sections(mdoc_data: Dict[str, Any], start_index: int = 0) -> Dict[str, Any]:
    """Renumber all Z sections sequentially starting from start_index."""
    old_z_values = sorted(mdoc_data['z_sections'].keys())
    new_z_sections = {}
    for i, old_z in enumerate(old_z_values):
        new_z = start_index + i
        new_z_sections[new_z] = mdoc_data['z_sections'][old_z]
    mdoc_data['z_sections'] = new_z_sections
    return mdoc_data


def insert_z_section_at_position(mdoc_data: Dict[str, Any], section_data: Dict[str, Any],
                                 position: int, renumber: bool = True) -> bool:
    """Insert a new Z section at a specific position."""
    current_z_values = sorted(mdoc_data['z_sections'].keys())

    if position < 0 or position > len(current_z_values):
        return False

    new_z_sections = {}
    for i, old_z in enumerate(current_z_values):
        if i == position:
            new_z_sections[i] = section_data.copy()
            new_z_sections[i + 1] = mdoc_data['z_sections'][old_z]
        elif i < position:
            new_z_sections[i] = mdoc_data['z_sections'][old_z]
        else:
            new_z_sections[i + 1] = mdoc_data['z_sections'][old_z]

    if position == len(current_z_values):
        new_z_sections[position] = section_data.copy()

    mdoc_data['z_sections'] = new_z_sections

    if renumber:
        renumber_z_sections(mdoc_data, start_index=0)

    return True


def write_mdoc_file(mdoc_data: Dict[str, Any], output_path: Union[str, Path], preserve_comments: bool = True) -> None:
    """Write modified mdoc data back to a file."""
    output_path = Path(output_path)

    original_comments = []
    if preserve_comments and output_path.exists():
        with open(output_path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line.startswith('[T = '):
                    original_comments.append(line)

    try:
        with open(output_path, 'w', encoding='utf-8') as f:
            for key, value in mdoc_data['header'].items():
                f.write(f"{key} = {_format_value_for_mdoc(value)}\n")

            if preserve_comments and original_comments:
                f.write("\n")
                for comment in original_comments:
                    f.write(f"{comment}\n")

            for z_value in sorted(mdoc_data['z_sections'].keys()):
                f.write(f"\n[ZValue = {z_value}]\n")
                section_data = mdoc_data['z_sections'][z_value]
                for key, value in section_data.items():
                    f.write(f"{key} = {_format_value_for_mdoc(value)}\n")

    except IOError as e:
        raise IOError(f"Failed to write mdoc file: {e}")


def copy_mdoc_with_modifications(input_path: Union[str, Path], output_path: Union[str, Path],
                                modifications: Dict[str, Any]) -> None:
    """Copy an mdoc file with modifications applied."""
    mdoc_data = parse_mdoc_file(input_path)

    if 'header' in modifications:
        for key, value in modifications['header'].items():
            set_header_value(mdoc_data, key, value)

    if 'all_z_sections' in modifications:
        for key, value in modifications['all_z_sections'].items():
            update_all_z_sections(mdoc_data, key, value)

    if 'z_sections' in modifications:
        update_multiple_z_sections(mdoc_data, modifications['z_sections'])

    if 'tilt_ranges' in modifications:
        for (min_angle, max_angle), updates in modifications['tilt_ranges'].items():
            for key, value in updates.items():
                update_tilt_range(mdoc_data, min_angle, max_angle, key, value)

    if 'tilt_angles' in modifications:
        tolerance = modifications.get('tilt_tolerance', 0.1)
        for target_angle, updates in modifications['tilt_angles'].items():
            for key, value in updates.items():
                set_value_by_tilt_angle(mdoc_data, target_angle, key, value, tolerance)

    write_mdoc_file(mdoc_data, output_path)


def print_mdoc_summary(mdoc_data: Dict[str, Any]) -> None:
    """Print a summary of the mdoc file contents."""
    print("MDOC File Summary")
    print("=" * 50)

    print("\nHeader Information:")
    for key, value in mdoc_data['header'].items():
        print(f"  {key}: {value}")

    z_values = get_all_z_values(mdoc_data)
    print(f"\nFound {len(z_values)} Z sections: {z_values}")

    tilt_angles = get_tilt_angles(mdoc_data)
    if tilt_angles:
        min_tilt = min(tilt_angles.values())
        max_tilt = max(tilt_angles.values())
        print(f"Tilt angle range: {min_tilt:.2f}° to {max_tilt:.2f}°")

    if z_values:
        example_z = z_values[0]
        print(f"\nExample Z section ({example_z}):")
        example_data = get_z_section(mdoc_data, example_z)
        for key, value in list(example_data.items())[:5]:
            print(f"  {key}: {value}")
        if len(example_data) > 5:
            print(f"  ... and {len(example_data) - 5} more fields")
